name: Generate Datas

on:
  schedule:
    - cron: "17 */12 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: snake-output-${{ github.repository }}
  cancel-in-progress: false

jobs:
  build:
    name: Generate contribution snake
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Generate SVG
        uses: Platane/snk/svg-only@d8f6715049803e982ee5ff501b6b9b7d5deeb09b # v3.5.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publish SVG
        uses: crazy-max/ghaction-github-pages@1d6ee9b181a81033a16bd707a1401afa978daab4 # v5.0.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          allow_empty_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
